Updated "Add Friends" Button
Snap-Engineering-Academy-2024/SnapChatStarter pull request #17
Opened 2024-07-23 22:39 UTC by malena-3

1) Added functionality to the "Add Friends" button - When button, in the top right corner of the ChatScreen (can be found in Header.js),  is pressed you're taken to a new screen: AddFriendScreen.js.
2) Added new screen called AddFriendScreen.js which shows the possible friends the user can add.
    With:
     - Sliding Horizontal Quick Add. Added new component "AddFriendBitmoji.js" with Bitmoji profile pictures 
       and a "quick add" button.
     - A "Other Friends" List. A vertical sliding list of usernames and user profile pictures that will take you to 
       the User's profile when pressed.

2024-07-31 21:25 UTC, malena-3 commented
Step One:
![Screenshot 2024-07-31 at 2 01 52 PM](https://github.com/user-attachments/assets/15bf881e-4db5-4003-8e00-56631c12b0a3)

1) From the profiles table, click the insert button.
2) Click the insert column

Step Two:
![Screenshot 2024-07-31 at 2 14 22 PM](https://github.com/user-attachments/assets/a391c0f5-1419-4fe2-8311-c5ba7c1f9cf3)

3) Name it “friend_ids”
4) Type will be T uuid
5) Check of Define as Array

Step Three:
![Screenshot 2024-07-31 at 2 15 51 PM](https://github.com/user-attachments/assets/42adcf56-0719-4b4f-b416-b01273e34c64)

6) Constraints - Allow for it to be nullable
7) Click save to complete !

2024-07-31 23:03 UTC, bakerfugu requested changes
please review comments and commit with new changes

2024-07-31 23:03 UTC, bakerfugu commented on src/screens/AddFriendScreen.js
> +      /> */}
Add a comment explaining what this is / why this commented code was left here

2024-07-31 23:03 UTC, bakerfugu commented on src/screens/ChatScreen.js
> +      <Header title="Chattt" />
change back to `Chat`

2024-07-31 23:04 UTC, bakerfugu commented
And move instructions with images to top comment so it's easier for people to see

2024-08-01 17:16 UTC, bakerfugu approved these changes
Looks good

2024-08-01 17:32 UTC, malena-3 commented on src/screens/AddFriendScreen.js
Commented out code is an additional section for the "Add Friends" page. A list of contacts with pfps and add button.

2024-08-01 17:42 UTC, merged